color: true
dry-run: null
hookfiles: null
language: php
require: null
server: 'php -S 127.0.0.1:8000 -t public/'
server-wait: 3
init: false
custom: {}
names: false
only: [
  "User Authentication API > Register User Collection > Register a new user",
  "User Authentication API > Login User Collection > Login into the system and get the JWT token",
  "User Resource API > Logged User Collection > Get the Token's Owner User",
  "User Resource API > User By ID Collection > Get a user by its ID",
  "Application Authentication API > Application Collection > Register a new application",
  "Application Authentication API > Application Collection > Login into the system and get the JWT token",
  "Application Resource API > Application Collection > Get All Registed Applications",
  "Application Resource API > Logged Application Collection > Get the Token's Owner Application",
  "Application Resource API > Application By ID Collection > Get a user by its ID"
]
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/boilerplate.apib
endpoint: 'http://127.0.0.1:8000/api/v1'
